service: example-service
 
frameworkVersion: '3'

provider:
  name: aws
  ecr:
    # Images that will be built locally and uploaded to ECR
    images:
      testimage:
        path: ./
 
functions:
  my_first_function:
    image:
      name: testimage
    events:
      - http:
          path: /
          method: get
      - http:
          path: /
          method: post